[package]
name = "paperspigot-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
bytes = "1.6.1"
tokio-util = { version = "0.7.11", features = ["codec"] }
tokio-stream = { version = "0.1.15", features = ["full"] }
futures = "0.3"